import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


import { GlobalStyle } from '../styles/GlobalStyle';

export default function Home() {
  return (
    <div>

      
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by apalacios" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <p>Home Page</p>

      

        
        

       
    </div>
  )
}

