import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


import { getAllFilesMetadata } from '../lib/mdx'

export default function Home({ posts }) {
  console.log('aaa')
  console.log(posts)
  return (
    <div>

        <Head>
          <title>Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>



        <main>
          <di>

            {posts.map(post => (
              <Link key={post.slug} href={`/${post.slug}`}>
                <a>
                  <Image src={`/images/icons/${post.languaje}.png`} alt='Logo' width={100} height={100}/>
                  <h2> {post.title} &rarr;</h2>
                  <p>{post.date}</p>
                </a>
              </Link> 
            ))}
            
          </di>
        </main>

    </div>
  )
}

export async function getStaticProps(){
  const posts = await getAllFilesMetadata()
  console.log(posts)
  return{
    props: {posts}
  }
}
